name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemShatalov/buildozer-action@v1.2
        with:
          workdir: .
          buildozer_version: master
