name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_display_name: AirHockeyStark

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AirHockey_Build
          path: bin/*.apk

